### ISSUE TITLE
Stardoc crashes when interacting with `apple_common` global

### ISSUE THREAD

**Issue by achew22** [bazelbuild/stardoc#76]
When Stardoc encounters the [following bit of code](https://github.com/bazelbuild/rules_go/blob/99e0cf0e35f21ae9ba601e3c42d133c23abf1c25/go/platform/apple.bzl#L16) in `rules_go`,

```bzl
_PLATFORMS = {
    "armv7-apple-ios": (apple_common.platform.ios_device, apple_common.platform_type.ios),
    "armv7-apple-tvos": (apple_common.platform.tvos_device, apple_common.platform_type.tvos),
    "armv7k-apple-watchos": (apple_common.platform.watchos_device, apple_common.platform_type.watchos),
    "arm64-apple-ios": (apple_common.platform.ios_device, apple_common.platform_type.ios),
    "arm64-apple-tvos": (apple_common.platform.tvos_device, apple_common.platform_type.tvos),
    "i386-apple-ios": (apple_common.platform.ios_simulator, apple_common.platform_type.ios),
    "i386-apple-tvos": (apple_common.platform.tvos_simulator, apple_common.platform_type.tvos),
    "i386-apple-watchos": (apple_common.platform.watchos_simulator, apple_common.platform_type.watchos),
    "x86_64-apple-ios": (apple_common.platform.ios_simulator, apple_common.platform_type.ios),
    "x86_64-apple-tvos": (apple_common.platform.ios_simulator, apple_common.platform_type.tvos),
    "x86_64-apple-watchos": (apple_common.platform.watchos_simulator, apple_common.platform_type.watchos),
}
```

it throws the following error:

```
SUBCOMMAND: # //go:def-docs [action 'Generating proto for Starlark doc for def-docs', configuration: faff19e6fd939f490ac11578d94024c6b7a032836cde039fd5edd28b838194e8, execution platform: @local_config_platform//:host]
(cd <snip> && \
  exec env - \
  bazel-out/host/bin/external/io_bazel_stardoc/stardoc/stardoc '--input=//go:def.bzl' '--workspace_name=io_bazel_rules_go' '--dep_roots=.' '--dep_roots=external/io_bazel_rules_go' '--output=bazel-out/k8-fastbuild/bin/go/def-docs.raw')
ERROR: <snip>/rules_go/go/BUILD.bazel:61:8: Generating proto for Starlark doc for def-docs failed (Exit 1) stardoc failed: error executing command bazel-out/host/bin/external/io_bazel_stardoc/stardoc/stardoc '--input=//go:def.bzl' '--workspace_name=io_bazel_rules_go' '--dep_roots=.' '--dep_roots=external/io_bazel_rules_go' ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
com.google.devtools.build.skydoc.SkydocMain$StarlarkEvaluationException: Starlark evaluation error
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:423)
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:397)
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:397)
        at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:255)
        at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:158)
Caused by: Traceback (most recent call last):
        File "./go/platform/apple.bzl", line 16, column 46, in <toplevel>
                "armv7-apple-ios": (apple_common.platform.ios_device, apple_common.platform_type.ios),
Error:
        at net.starlark.java.eval.Starlark.errorf(Starlark.java:555)
        at net.starlark.java.eval.Starlark.getattr(Starlark.java:606)
        at net.starlark.java.eval.Eval.evalDot(Eval.java:530)
        at net.starlark.java.eval.Eval.eval(Eval.java:446)
        at net.starlark.java.eval.Eval.evalList(Eval.java:704)
        at net.starlark.java.eval.Eval.eval(Eval.java:466)
        at net.starlark.java.eval.Eval.evalDict(Eval.java:509)
        at net.starlark.java.eval.Eval.eval(Eval.java:444)
        at net.starlark.java.eval.Eval.execAssignment(Eval.java:108)
        at net.starlark.java.eval.Eval.exec(Eval.java:260)
        at net.starlark.java.eval.Eval.execStatements(Eval.java:80)
        at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:64)
        at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:155)
        at net.starlark.java.eval.Starlark.fastcall(Starlark.java:509)
        at net.starlark.java.eval.Starlark.execFileProgram(Starlark.java:779)
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:420)
        ... 4 more
```

To view, clone, and test this change, please see my CL to be: https://github.com/achew22/rules_go/pull/new/stardoc
and `bazel build //go:def-docs`

**Comment by alandonovan** [comment]
There are two bugs here. The first is that the error message is terrible: instead of showing you the names of various Java functions inside Skydoc, it should report the Starlark stack and (crucially) the error message. The second bug is that the failure, of the `.ios_device` operator, is spurious: it is caused by a mismatch between the fake environment used by skydoc and the reality of bazel.  Compare:

https://github.com/bazelbuild/bazel/blob/750c938ad180d69cce95af704738360677269d85/src/main/java/com/google/devtools/build/skydoc/fakebuildapi/apple/FakeAppleCommon.java#L62
https://github.com/bazelbuild/bazel/blob/450c7ad65bfcffebf753159ee2b617e557ffb4fd/src/main/java/com/google/devtools/build/lib/rules/apple/ApplePlatform.java#L194

The solution to the first bug is to change the exception handling in skydoc. The solution to the second is to reimplement skydoc as a client of bazel query, which would load .bzl files and print information about them so that skydoc doesn't need all this fakery. As a short-term hack, one could modify the fake environment, but this is only postponing the inevitable.

**Comment by c-parsons** [comment]
Is the plan to reimplement skydoc as a client of bazel query something that's being actively worked on or is on a roadmap? If not, we may want to modify the fake environment regardless. It's a quick change.

**Comment by achew22** [comment]
@c-parsons I'm not sure exactly how one would go about doing that. I presume [this](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/skydoc/fakebuildapi/apple/FakeAppleCommon.java) is the fake that would need to be modified. More specifically, I'm not sure why [this](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/skydoc/fakebuildapi/apple/FakeAppleCommon.java;l=70) line is insufficient?

**Comment by achew22** [comment]
Friendly ping

**Comment by alandonovan** [comment]
> Is the plan to reimplement stardoc as a client of bazel query something that's being actively worked on? 

It's on the roadmap, but it's blocked behind several other changes, so it won't happen for a while.

Modifying the fake environment is the expedient move.

**Comment by c-parsons** [comment]
> @c-parsons I'm not sure exactly how one would go about doing that. I presume [this](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/skydoc/fakebuildapi/apple/FakeAppleCommon.java) is the fake that would need to be modified.

Yes, particularly [this](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/skydoc/fakebuildapi/apple/FakeAppleCommon.java;l=60;drc=750c938ad180d69cce95af704738360677269d85) demonstrates how one should return a non-empty struct for `getPlatformStruct`.

> More specifically, I'm not sure why [this](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/skydoc/fakebuildapi/apple/FakeAppleCommon.java;l=70) line is insufficient?

Lets consider the evaluation of `(apple_common.platform.ios_device, apple_common.platform_type.ios)`.
The latter is fine, because, in the fake environment, `apple_common.platform_type` does have a field "ios". However, `apple_common.platform` is equivalent to `struct()`, thus an error is thrown.

**Comment by achew22** [comment]
@c-parsons is this what you were expecting https://github.com/bazelbuild/bazel/pull/12383?

**Comment by achew22** [comment]
Friendly ping @c-parsons

**Comment by c-parsons** [comment]
Related issue: https://github.com/bazelbuild/stardoc/issues/83

Apologies that response has been so slow on this issue.
Maintenance of this repository is changing hands, and thus some issues have fallen through the cracks.
