### ISSUE TITLE
Starlark evaluation error

### ISSUE THREAD

**Issue by mobileink** [bazelbuild/stardoc#83]
I've got two stardoc rules that are almost exactly the same, except that they process different bzl files. One works, the other fails with `Stardoc documentation generation failed: Starlark evaluation error`.  That's it.  I've got --verbose_failures and --sandbox_debug enabled.

How can I debug this?

**Comment by mobileink** [comment]
Is this project still maintained?

**Comment by brandjon** [comment]
Hi Gregg, sorry for the delay. Stardoc is maintained but we have plans to reimplement it as an extension of Bazel. In the meantime, we can take on workflow-breaking bugs but not necessarily feature requests.

I'm not sure why you're not getting a starlark traceback in the error. The message comes from [here](https://github.com/bazelbuild/bazel/blob/19fe9f087f1122c986a779b29b1c7832507868ea/src/main/java/com/google/devtools/build/skydoc/SkydocMain.java#L172-L173). What version of Bazel are you using?

It's possible stardoc just won't work on a certain bzl file because its mocking of Bazel's evaluation is inherently imperfect. (This will be fixed by the aforementioned reimplementation.) But you should definitely be able to get an error telling you the offending location in a bzl file.

**Comment by alandonovan** [comment]
The current behavior was implemented by c5dc4406f3517d30b0b5f333a51437cd03321744 to address 
https://github.com/bazelbuild/skydoc/issues/175, which asked for exactly the opposite behavior---the removal of the stack trace. Personally I think one should never discard a stack trace because it makes debugging impossible, as you discovered, but this was done by a previous maintainer. Perhaps he can shed light on the decision.

@c-parsons

**Comment by alandonovan** [comment]
I agree the tool should display the Starlark stack in case of error, and have sent a PR.

**Comment by c-parsons** [comment]
The original tracking issue which removed stack traces,
bazelbuild/skydoc#175 <https://github.com/bazelbuild/skydoc/issues/175> called
for removal of simply the stack trace, not the error message.

As is remarked in that issue, the following is the only useful piece of the
example error message:

```
redacted.bzl:5:1: file '//foo.bzl' does not contain symbol 'redacted_symbol'
```

The stack trace itself, while it may be useful for stardoc maintainers, is
typically unhelpful for starlark authors using the tool.

I believe that Starlark error reporting has changed in-place since that
fix, and it has thus removed the helpful-to-users portion of this error
message and replaced it with merely "Starlark Evaluation Error", which is
the crux of this issue.
I can delve deeper if you think it's necessary.

**Comment by alandonovan** [comment]
Yeah, sorry, I realized my mistake (that the stack was Java not Starlark) only after hitting "comment". I've mailed cr/350353793 to display the Starlark stack.

**Comment by mobileink** [comment]
FWIW I managed to find the problem with a little trial and error. It was a typo in the .bzl file that is `input` to the stardoc rule, in one of the load statements.  Or maybe in one of the assignments that export the aliases, I forge which.

**Comment by brandjon** [comment]
(I assume the commit on @aiuto's fork closed this issue because he has write privileges in this repo, and the bazel commit exporting bot does not.)
